### Problem Definition

The goal of this project is to build a model that can predict whether a given data record belongs to class 0 or 1 
using the available input features.
This is likely related to customer behavior such as churn or transaction prediction.

### Import Libraries

In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv("train(1).csv")
df

,ID_code,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,...,var_190,var_191,var_192,var_193,var_194,var_195,var_196,var_197,var_198,var_199
0,train_0,0,8.9255,-6.7863,11.9081,5.0930,11.4607,-9.2834,5.1187,18.6266,...,4.4354,3.9642,3.1364,1.6910,18.5227,-2.3978,7.8784,8.5635,12.7803,-1.0914
1,train_1,0,11.5006,-4.1473,13.8588,5.3890,12.3622,7.0433,5.6208,16.5338,...,7.6421,7.7214,2.5837,10.9516,15.4305,2.0339,8.1267,8.7889,18.3560,1.9518
2,train_2,0,8.6093,-2.7457,12.0805,7.8928,10.5825,-9.0837,6.9427,14.6155,...,2.9057,9.7905,1.6704,1.6858,21.6042,3.1417,-6.5213,8.2675,14.7222,0.3965
3,train_3,0,11.0604,-2.1518,8.9522,7.1957,12.5846,-1.8361,5.8428,14.9250,...,4.4666,4.7433,0.7178,1.4214,23.0347,-1.2706,-2.9275,10.2922,17.9697,-8.9996
4,train_4,0,9.8369,-1.4834,12.8746,6.6375,12.2772,2.4486,5.9405,19.2514,...,-1.4905,9.5214,-0.1508,9.1942,13.2876,-1.5121,3.9267,9.5031,17.9974,-8.8104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,train_199995,0,11.4880,-0.4956,8.2622,3.5142,10.3404,11.6081,5.6709,15.1516,...,6.1415,13.2305,3.9901,0.9388,18.0249,-1.7939,2.1661,8.5326,16.6660,-17.8661
199996,train_199996,0,4.9149,-2.4484,16.7052,6.6345,8.3096,-10.5628,5.8802,21.5940,...,4.9611,4.6549,0.6998,1.8341,22.2717,1.7337,-2.1651,6.7419,15.9054,0.3388
199997,train_199997,0,11.2232,-5.0518,10.5127,5.6456,9.3410,-5.4086,4.5555,21.5571,...,4.0651,5.4414,3.1032,4.8793,23.5311,-1.5736,1.2832,8.7155,13.8329,4.1995
199998,train_199998,0,9.7148,-8.6098,13.6104,5.7930,12.5173,0.5339,6.0479,17.0152,...,2.6840,8.6587,2.7337,11.1178,20.4158,-0.0786,6.7980,10.0342,15.5289,-13.9001


Insights-->
The dataset is loaded into a DataFrame for analysis.
It is the starting point of the ML pipeline.                                      

### Basic Checks

In [3]:
df.head()

,ID_code,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,...,var_190,var_191,var_192,var_193,var_194,var_195,var_196,var_197,var_198,var_199
0,train_0,0,8.9255,-6.7863,11.9081,5.0930,11.4607,-9.2834,5.1187,18.6266,...,4.4354,3.9642,3.1364,1.6910,18.5227,-2.3978,7.8784,8.5635,12.7803,-1.0914
1,train_1,0,11.5006,-4.1473,13.8588,5.3890,12.3622,7.0433,5.6208,16.5338,...,7.6421,7.7214,2.5837,10.9516,15.4305,2.0339,8.1267,8.7889,18.3560,1.9518
2,train_2,0,8.6093,-2.7457,12.0805,7.8928,10.5825,-9.0837,6.9427,14.6155,...,2.9057,9.7905,1.6704,1.6858,21.6042,3.1417,-6.5213,8.2675,14.7222,0.3965
3,train_3,0,11.0604,-2.1518,8.9522,7.1957,12.5846,-1.8361,5.8428,14.9250,...,4.4666,4.7433,0.7178,1.4214,23.0347,-1.2706,-2.9275,10.2922,17.9697,-8.9996
4,train_4,0,9.8369,-1.4834,12.8746,6.6375,12.2772,2.4486,5.9405,19.2514,...,-1.4905,9.5214,-0.1508,9.1942,13.2876,-1.5121,3.9267,9.5031,17.9974,-8.8104


In [4]:
df.tail()

,ID_code,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,...,var_190,var_191,var_192,var_193,var_194,var_195,var_196,var_197,var_198,var_199
199995,train_199995,0,11.4880,-0.4956,8.2622,3.5142,10.3404,11.6081,5.6709,15.1516,...,6.1415,13.2305,3.9901,0.9388,18.0249,-1.7939,2.1661,8.5326,16.6660,-17.8661
199996,train_199996,0,4.9149,-2.4484,16.7052,6.6345,8.3096,-10.5628,5.8802,21.5940,...,4.9611,4.6549,0.6998,1.8341,22.2717,1.7337,-2.1651,6.7419,15.9054,0.3388
199997,train_199997,0,11.2232,-5.0518,10.5127,5.6456,9.3410,-5.4086,4.5555,21.5571,...,4.0651,5.4414,3.1032,4.8793,23.5311,-1.5736,1.2832,8.7155,13.8329,4.1995
199998,train_199998,0,9.7148,-8.6098,13.6104,5.7930,12.5173,0.5339,6.0479,17.0152,...,2.6840,8.6587,2.7337,11.1178,20.4158,-0.0786,6.7980,10.0342,15.5289,-13.9001
199999,train_199999,0,10.8762,-5.7105,12.1183,8.0328,11.5577,0.3488,5.2839,15.2058,...,8.9842,1.6893,0.1276,0.3766,15.2101,-2.4907,-2.2342,8.1857,12.1284,0.1385


In [5]:
df.describe()

,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,var_8,...,var_190,var_191,var_192,var_193,var_194,var_195,var_196,var_197,var_198,var_199
count,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,...,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000
mean,0.100490,10.679914,-1.627622,10.715192,6.796529,11.078333,-5.065317,5.408949,16.545850,0.284162,...,3.234440,7.438408,1.927839,3.331774,17.993784,-0.142088,2.303335,8.908158,15.870720,-3.326537
std,0.300653,3.040051,4.050044,2.640894,2.043319,1.623150,7.863267,0.866607,3.418076,3.332634,...,4.559922,3.023272,1.478423,3.992030,3.135162,1.429372,5.454369,0.921625,3.010945,10.438015
min,0.000000,0.408400,-15.043400,2.117100,-0.040200,5.074800,-32.562600,2.347300,5.349700,-10.505500,...,-14.093300,-2.691700,-3.814500,-11.783400,8.694400,-5.261000,-14.209600,5.960600,6.299300,-38.852800
25%,0.000000,8.453850,-4.740025,8.722475,5.254075,9.883175,-11.200350,4.767700,13.943800,-2.317800,...,-0.058825,5.157400,0.889775,0.584600,15.629800,-1.170700,-1.946925,8.252800,13.829700,-11.208475
50%,0.000000,10.524750,-1.608050,10.580000,6.825000,11.108250,-4.833150,5.385100,16.456800,0.393700,...,3.203600,7.347750,1.901300,3.396350,17.957950,-0.172700,2.408900,8.888200,15.934050,-2.819550
75%,0.000000,12.758200,1.358625,12.516700,8.324100,12.261125,0.924800,6.003000,19.102900,2.937900,...,6.406200,9.512525,2.949500,6.205800,20.396525,0.829600,6.556725,9.593300,18.064725,4.836800
max,1.000000,20.315000,10.376800,19.353000,13.188300,16.671400,17.251600,8.447700,27.691800,10.151300,...,18.440900,16.716500,8.402400,18.281800,27.928800,4.272900,18.321500,12.000400,26.079100,28.500700


In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Columns: 202 entries, ID_code to var_199
dtypes: float64(200), int64(1), object(1)
memory usage: 308.2+ MB


In [7]:
df.shape

(200000, 202)

### Data Preprocessing

In [8]:
df.isnull().sum()

ID_code    0
target     0
var_0      0
var_1      0
var_2      0
          ..
var_195    0
var_196    0
var_197    0
var_198    0
var_199    0
Length: 202, dtype: int64

## Drop the unwanted column

In [3]:
df.drop("ID_code",axis=1,inplace=True)

### Split data into x and y

In [4]:
X = df.drop("target", axis=1)
y = df["target"]

In [11]:
y.shape

(200000,)

### Splitting Data into Train Test split

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42)

In [6]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(160000, 200)
(40000, 200)
(160000,)
(40000,)


### Feature scaling 

In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [8]:
X_train.shape

(160000, 200)

## Creating Model

In [9]:
from sklearn.linear_model import LogisticRegression
# Create model
model = LogisticRegression(max_iter=100,
    random_state=42)
# Train model
model.fit(X_train, y_train)
# Predict
y_pred_lg = model.predict(X_test)

In [17]:
y_pred_lg

array([0, 0, 0, ..., 0, 0, 0])

In [10]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [11]:
accuracy_score(y_test,y_pred_lg)

0.9131

In [12]:
confusion_matrix(y_test,y_pred_lg)

array([[35420,   483],
       [ 2993,  1104]])

In [13]:
y_prob1 = model.predict_proba(X_test)[:, 1]

In [14]:
for t in [0.2, 0.3, 0.4, 0.5, 0.6,0.75,0.8,0.9]:
    y_pred = (y_prob1 >= t).astype(int)
    
    print(f"\nThreshold: {t}")
    print(confusion_matrix(y_test, y_pred))


Threshold: 0.2
[[32499  3404]
 [ 1643  2454]]

Threshold: 0.3
[[34163  1740]
 [ 2177  1920]]

Threshold: 0.4
[[34978   925]
 [ 2631  1466]]

Threshold: 0.5
[[35420   483]
 [ 2993  1104]]

Threshold: 0.6
[[35675   228]
 [ 3298   799]]

Threshold: 0.75
[[35832    71]
 [ 3697   400]]

Threshold: 0.8
[[35866    37]
 [ 3816   281]]

Threshold: 0.9
[[35899     4]
 [ 4019    78]]


In [15]:
y_pred = (y_prob1 > 0.3).astype(int)

In [16]:
from sklearn.metrics import roc_auc_score
y_pred1 = roc_auc_score(y_test,y_prob1)
y_pred1

np.float64(0.859678164508442)

In [17]:
print(classification_report(y_test,y_pred_lg))


              precision    recall  f1-score   support

           0       0.92      0.99      0.95     35903
           1       0.70      0.27      0.39      4097

    accuracy                           0.91     40000
   macro avg       0.81      0.63      0.67     40000
weighted avg       0.90      0.91      0.90     40000



### XGBoost Classifier

In [27]:
from xgboost import XGBClassifier
xgb_clf=XGBClassifier(n_estimators=500,
    max_depth=4,
    learning_rate=0.1,
    scale_pos_weight=6,
    random_state=42)

In [28]:
xgb_clf.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=4,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=500,
              n_jobs=None, num_parallel_tree=None, ...)

In [29]:
y_pred_xgb=xgb_clf.predict(X_test) 
# Model predicts outcomes on test data.
# Shows how model behaves on unseen data.

In [30]:
accuracy_score(y_test,y_pred_xgb)

0.891675

In [31]:
confusion_matrix(y_test,y_pred_xgb)

array([[33110,  2793],
       [ 1540,  2557]])

In [32]:
y_prob2 = xgb_clf.predict_proba(X_test)[:, 1]

In [34]:
for t in [0.2, 0.3, 0.4, 0.5, 0.6,0.75,0.8,0.9]:
    y_pred = (y_prob2 >= t).astype(int)
    
    print(f"\nThreshold: {t}")
    print(confusion_matrix(y_test, y_pred))


Threshold: 0.2
[[21469 14434]
 [  299  3798]]

Threshold: 0.3
[[27363  8540]
 [  664  3433]]

Threshold: 0.4
[[30945  4958]
 [ 1096  3001]]

Threshold: 0.5
[[33110  2793]
 [ 1540  2557]]

Threshold: 0.6
[[34407  1496]
 [ 2021  2076]]

Threshold: 0.75
[[35495   408]
 [ 2771  1326]]

Threshold: 0.8
[[35676   227]
 [ 3070  1027]]

Threshold: 0.9
[[35866    37]
 [ 3657   440]]


In [35]:
y_pred = (y_prob2 > 0.3).astype(int)

In [36]:
from sklearn.metrics import roc_auc_score
y_pred2 = roc_auc_score(y_test,y_prob2)
y_pred2

np.float64(0.8855176088697918)

In [37]:
print(classification_report(y_test,y_pred_xgb))

              precision    recall  f1-score   support

           0       0.96      0.92      0.94     35903
           1       0.48      0.62      0.54      4097

    accuracy                           0.89     40000
   macro avg       0.72      0.77      0.74     40000
weighted avg       0.91      0.89      0.90     40000



# Problem Faced


#### High Dimensionality
Too many input variables compared to samples

#### Feature Distribution Complexity
Features may not follow normal distribution

#### Hidden Patterns
Relationships between features are not obvious

#### No Clear Correlation
Features have weak or no strong correlation with target